export {default as Home} from './home/Home'
export {default as Login} from './login/Login'
export {default as Register} from './register/Register'
export {default as Write} from './write/Write'
export {default as ProfilePage} from './profile/ProfilePage'
export {default as PostPage} from './postPage/PostPage'
export {default as Settings} from './settings/Settings'